set linesize 300;

SELECT * FROM MANAGER;
SELECT * FROM BRANCH;
SELECT * FROM COURSE;
SELECT * FROM BATCH;
SELECT * FROM TEACHER;
SELECT * FROM STUDENT;
SELECT * FROM SCHEDULE;
SELECT * FROM EXAM;
SELECT * FROM RESULT;